language: python
python:
    - "3.3"
install:
    - pip install matplotlib coveralls
script:
    - python -m unittest -v
    - python setup.py install
    - python setup.py sdist
    - coverage run --source=taskplot --branch runtests.py
after_success:
    - coveralls
